name: Clean install and build

on:
  workflow_call:

env:
  DATABASE_URI: ${{ secrets.DATABASE_URI }}
  PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          echo "This is the $DATABASE_URI environment variable"
          echo "This is the $PAYLOAD_SECRET environment variable"
          npm ci
          npm run build --if-present
