name: Initial checks

on:
  workflow_call:

jobs:
  check-pr:
    runs-on: ubuntu-latest
    name: Check pr
    steps:
      - uses: actions/checkout@v4
      - if: github.event_name == 'pull_request'
        run: |
          echo "Pull Request Detected!"
          echo "PR no: ${{ github.event.pull_request.number }}"
          echo "PR title: ${{ github.event.pull_request.title }}"

  check-secrets:
    runs-on: ubuntu-latest
    name: Check secrets
    env:
      TEST_VAR: some random value
      DATABASE_URI: ${{ github.event_name == 'pull_request' && secrets.DATABASE_URI_PR || secrets.DATABASE_URI }}
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      ORG_ID: ${{ secrets.ORG_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [ -z "$TEST_VAR" ]; then
            echo "Failed to retrieve test env variable"
            exit 1
          elif [ -z "$DATABASE_URI" ]; then
            echo "Missing DATABASE_URI secret"
            exit 1
          elif [ -z "$PAYLOAD_SECRET" ]; then
            echo "Missing PAYLOAD_SECRET secret"
            exit 1
          elif [ -z "$VERCEL_TOKEN" ]; then
            echo "Missing VERCEL_TOKEN secret"
            exit 1
          elif [ -z "$ORG_ID" ]; then
            echo "Missing ORG_ID secret"
            exit 1
          elif [ -z "$PROJECT_ID" ]; then
            echo "Missing PROJECT_ID secret"
            exit 1
          fi
