name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  build-deploy:
    needs: check
    runs-on: ubuntu-latest
    environment: production
    env:
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/build-npm.yml
      - name: Install vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy to vercel (prod)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
