name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  build-deploy:
    needs: check
    runs-on: ubuntu-latest
    environment: production
    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Install vercel CLI
        run: npm install --global vercel@latest
      - name: Build artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to vercel (prod)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
