name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://silviatan.com
    steps:
      - uses: actions/checkout@v4
      - name: Install vercel CLI
        run: npm install --global vercel@latest

      - name: Set env info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to vercel (prod)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
