name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  build:
    needs: check
    uses: ./.github/workflows/build-npm.yml
    secrets: inherit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to vercel (prod)
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
