name: Check for secrets

on:
  workflow_call:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: "${{ secrets.DATABASE_URI == '' }}"
        run: |
          echo "Missing DATABASE_URI secret"
          exit 1
      - if: "${{ secrets.PAYLOAD_SECRET == '' }}"
        run: |
          echo "Missing PAYLOAD_SECRET secret"
          exit 1
      - if: "${{ secrets.VERCEL_TOKEN  == '' }}"
        run: |
          echo "Missing VERCEL_TOKEN secret"
          exit 1
      - if: "${{ secrets.ORG_ID == '' }}"
        run: |
          echo "Missing ORG_ID secret"
          exit 1
      - if: "${{ secrets.PROJECT_ID == '' }}"
        run: |
          echo "Missing PROJECT_ID secret"
          exit 1
