name: Check for secrets

on:
  workflow_call:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    env:
      TEST_VAR: some random value
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      ORG_ID: ${{ secrets.ORG_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - run: |
          elif [ -z "$TEST_VAR" ]; then
            echo "Failed to retrieve test env variable"
            exit 1
          elif [ -z "$DATABASE_URI" ]; then
            echo "Missing DATABASE_URI secret"
            exit 1
          elif [ -z "$PAYLOAD_SECRET" ]; then
            echo "Missing PAYLOAD_SECRET secret"
            exit 1
          elif [ -z "$VERCEL_TOKEN" ]; then
            echo "Missing VERCEL_TOKEN secret"
            exit 1
          elif [ -z "$ORG_ID" ]; then
            echo "Missing ORG_ID secret"
            exit 1
          elif [ -z "$PROJECT_ID" ]; then
            echo "Missing PROJECT_ID secret"
            exit 1
          fi
