name: Try to get secrets

on:
  workflow_call:

env:
  DATABASE_URI: ${{ secrets.DATABASE_URI }}
  PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "This is the ${{ secrets.DATABASE_URI }} environment variable"
          echo "This is the ${{ secrets.PAYLOAD_SECRET }} environment variable"
          echo "This is the ${{ secrets.VERCEL_TOKEN }} environment variable"
          echo "This is the ${{ secrets.ORG_ID }} environment variable"
          echo "This is the ${{ secrets.PROJECT_ID }} environment variable"
